name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for main project
      run: dotnet restore "Blazor Lab Starter Code\Blazor Lab Starter Code.csproj"

    - name: Build main project
      run: dotnet build "Blazor Lab Starter Code\Blazor Lab Starter Code.csproj" 

    - name: Restore dependencies for test project
      run: dotnet restore "Tests\Blazor Lab Starter Code.Tests.csproj"

    - name: Test project
      run: dotnet test "Tests\Blazor Lab Starter Code.Tests.csproj"  
